title: OS2Kitos vejledninger
description: Dette er en side til OS2Kitos vejledninger
theme: just-the-docs
logo: "/assets/site/OS2kitos_logo.png"
favicon_ico: "/assets/site/favicon.ico"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

aux_links:
  Repository: https://github.com/os2kitos/kitos_docs
  Maintainers: ./MAINTAINERS
  Contribute: ./CONTRIBUTING
      
defaults:
  - scope:
      path: ""         # alle filer i hele repoet
      type: "pages"    # markdown-sider
    values:
      layout: "default"
